version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      non-major-revisions:
        update-types:
          - minor
          - patch
      major-revisions:
        update-types:
          - major
